spring:

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://project-db:5432/docker
    username: docker
    password: docker
    driverClassName: org.postgresql.Driver

    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      minimumIdle: 0
      max-lifetime: 1800000
      maximum-pool-size: 4

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/liquibase/changelog-master.xml
    default-schema: public
    user: docker
    password: docker

logging:
  level:
    liquibase: DEBUG

