name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission to Maven wrapper
        run: chmod +x mvnw

      - name: Build Docker image
        run: docker build -t inclusiveplanner-backend -f docker/Dockerfile .

      - name: Run Docker Compose for Integration Test
        run: |
          docker compose -f docker/docker-compose.yaml up --build -d

      - name: Wait for backend to become healthy
        run: |
          for i in {1..10}; do
            echo "Checking /health (attempt $i)..."
            if curl --fail http://localhost:8080/health; then
              echo "Backend is healthy."
              exit 0
            fi
            sleep 3
          done
          echo "Backend did not become healthy in time."
          docker compose logs
          exit 1

      - name: Run tests
        run: ./mvnw test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        if: github.ref == 'refs/heads/main'
        run: docker tag inclusiveplanner-backend ${{ secrets.DOCKER_USERNAME }}/inclusiveplanner:latest

      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/inclusiveplanner:latest
